version: '3'
services:
  pcl-container:
    image: elainasuki/ros:ros2-humble-full-v2
    container_name: ros2-humble-full
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OMP_WAIT_POLICY=passive
      - TERM=xterm-256color
    volumes:
      - ${XAUTHORITY}:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./../..:/home/Elaina/docker
      # - ~/.config/fish:/home/Elaina/.config/fish
    network_mode: host
    pid: "host" # 添加 pid 命名空间共享
    ipc: "host" # 添加 ipc 命名空间共享    
    privileged: true
    stdin_open: true
    tty: true
    user: "Elaina"
    #runtime: "nvidia"
    working_dir: "/home/Elaina" # 指定默认工作目录
